<%@ Page Language="C#" MasterPageFile="~/Master.master" AutoEventWireup="true" Inherits="CMS.Users" Title="Users" Codebehind="Users.aspx.cs" %>

<asp:Content ID="C" ContentPlaceHolderID="CPH1" runat="Server">
    
    <div class="settings">
        <h1>
            Create New User
        </h1>
        <asp:CreateUserWizard ID="CreateUserWizard1" runat="server" LoginCreatedUser="false">
            <WizardSteps>
                <asp:CreateUserWizardStep ID="CreateUserWizardStep1" runat="server" />
            </WizardSteps>
        </asp:CreateUserWizard>
        <asp:Label runat="server" ID="lblError" Text="Username is already taken" style="color:Red" visible="false" />
    </div>

    <h1>
        Edit Users
    </h1>
    <div class="settings">
        <asp:GridView runat="server" ID="gridUsers" AutoGenerateColumns="false" UseAccessibleHeader="true" CellPadding="4"
             HeaderStyle-HorizontalAlign="left" DataKeyNames="username" OnLoad="gridUsers_Load" AlternatingRowStyle-CssClass="alt" 
             AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
            <Columns>
                
                <asp:TemplateField HeaderText="Username">
                  <ItemTemplate>
                    <asp:Label runat="server" Text='<%# Eval("username") %>' />
                  </ItemTemplate>
                </asp:TemplateField>
                
                <asp:TemplateField HeaderText="Password">
                  <ItemTemplate>
                    **********
                  </ItemTemplate>
                </asp:TemplateField>
                
                <asp:TemplateField HeaderText="Email">
                  <ItemTemplate>
                    <asp:Label runat="server" Text='<%# Eval("email") %>' />
                  </ItemTemplate>
                  <EditItemTemplate>
                    <asp:TextBox runat="server" ID="txtEmail" Text='<%# Eval("email") %>' />
                  </EditItemTemplate>
                </asp:TemplateField>
                
                <asp:TemplateField HeaderText="Roles" ItemStyle-Wrap="false" ItemStyle-Width="100%" />
            </Columns>
            <HeaderStyle HorizontalAlign="Left" />
        </asp:GridView>
    </div>
    
</asp:Content>
